redis-standalone:
  host: localhost
  jedis:
    pool:
      min-idle: 5
      max-idle: 8
      max-active: 8
  port: 6379

---
# 개발 배포
spring:
  profiles: dev
redis-standalone:
  host: hotdeals-redis-single-service
  jedis:
    pool:
      min-idle: 10
      max-idle: 50
      max-active: 100
  port: 6379

---
# 상용 배포
spring:
  profiles: prod

redis-standalone:
  host: hotdeals-redis-single-service
  jedis:
    pool:
      min-idle: 10
      max-idle: 50
      max-active: 100
  port: 6379
