apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hotdeals-event-management-deployment-hpa
spec:
<<<<<<< HEAD
  minReplicas: 2
  maxReplicas: 5
=======
  minReplicas: 10
  maxReplicas: 20
>>>>>>> cassandra
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hotdeals-event-management-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50