apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotdeals-event-management-deployment
  namespace: hotdeals
  labels:
    app: hotdeals-event-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotdeals-event-management
  replicas: 1
  template:
    metadata:
      labels:
        app: hotdeals-event-management
    spec:
      containers:
      - name: hotdeals-event-management
        image: docker.io/ktdatagarage/hotdeals-event-management:latest
        env:
        - name: http
          value: "8080"
        - name: JAVA_OPTS
          value: >-
            -Djava.security.egd=file:/dev/./urandom -Dserver.port=8080
            -Dfile.encoding=UTF8 -Dclient.encoding.override=UTF-8
            -Duser.timezone=GMT+09:00 -Dsun.java2d.opengl=false
            -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true
            -Dspring.profiles.active=prod
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: spring-8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
