apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hotdeals-event-management-deployment-hpa
spec:
  minReplicas: 5
  maxReplicas: 15
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hotdeals-event-management-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50