def label = "hotdeals-event-management-${UUID.randomUUID().toString()}"

podTemplate(label: label,
    containers: [
        containerTemplate(name: 'maven', image: 'maven:3.3.9-jdk-8-alpine', ttyEnabled: true, command: 'cat'),
        containerTemplate(name: 'docker', image: 'docker:stable', ttyEnabled: true, command: 'cat'),
        containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:latest', command: 'cat', ttyEnabled: true)
    ], volumes: [hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')]
) {
    node(label) {
        stage('Get Source') {
            git branch: 'develop', credentialsId: '', url: 'https://github.com/sky01126/hotdeals.git'
        }

        def pom = readMavenPom file: 'pom.xml'

        def props           = readProperties  file:'hotdeals-event-management/deployment/pipeline.properties'
        def tag             = pom.version
        def gitSrc          = props['gitSrc']
        def dockerRegistry  = props['dockerRegistry']
        def image           = props['image']
        def deployment      = props['deployment']
        def service         = props['service']
        def selector        = props['selector']
        def namespace       = props['namespace']
        def prefix          = props['prefix']
        def dockerHub       = props['dockerHub']

        printf("Version: %s", tag)

        stage('Build Maven project') {
            container('maven') {
                sh "echo ${tag}"
            }
        }
    }
}
